// <auto-generated />
using System;
using InfrastructureLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InfrastructureLayer.Migrations
{
    [DbContext(typeof(SNMDbContext))]
    [Migration("20260623124801_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DomainLayer.Entities.Booth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal?>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValueSql("0")
                        .HasComment("Cache điểm trung bình review, cập nhật qua trigger hoặc job định kỳ");

                    b.Property<string>("BoothCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BoothName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("BoothOwnerId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("CloseTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<decimal?>("MapPositionX")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("MapPositionY")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("NightMarketId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("OpenTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime?>("PackageExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PackageName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PaymentQRImage")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SlotNumber")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'Pending'::character varying")
                        .HasComment("Pending: chờ Admin duyệt | Active: hoạt động | Inactive: tạm ngừng | Suspended: bị khóa do vi phạm");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("Booth_pkey");

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.HasIndex("ZoneId");

                    b.HasIndex(new[] { "NightMarketId" }, "idx_booth_nightmarket");

                    b.HasIndex(new[] { "BoothOwnerId" }, "idx_booth_owner");

                    b.ToTable("Booth", null, t =>
                        {
                            t.HasComment("Gian hàng ẩm thực - thực thể trung tâm, mỗi gian hàng thuộc 1 NightMarket và do 1 User (BoothOwner) quản lý");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.BoothDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("BoothId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'Pending'::character varying");

                    b.HasKey("Id")
                        .HasName("BoothDocuments_pkey");

                    b.HasIndex("BoothId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("BoothDocuments", t =>
                        {
                            t.HasComment("Giấy tờ pháp lý của gian hàng để Admin xác minh trước khi cho phép hoạt động");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.BoothImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("BoothId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("BoothImages_pkey");

                    b.HasIndex("BoothId");

                    b.ToTable("BoothImages", t =>
                        {
                            t.HasComment("Thư viện ảnh (gallery) của gian hàng");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.BoothLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("BoothId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Xcoordinate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("XCoordinate");

                    b.Property<decimal>("Ycoordinate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("YCoordinate");

                    b.HasKey("Id")
                        .HasName("BoothLocations_pkey");

                    b.HasIndex("LayoutId");

                    b.HasIndex(new[] { "BoothId" }, "BoothLocations_BoothId_key")
                        .IsUnique();

                    b.ToTable("BoothLocations", t =>
                        {
                            t.HasComment("Vị trí cụ thể (tọa độ) của 1 gian hàng trên 1 sơ đồ mặt bằng");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.BoothPaymentInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("BankAccountHolder")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("BoothId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("PaymentType")
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasComment("BankTransfer | VNPay | MoMo | ZaloPay | Payos");

                    b.Property<string>("QrimageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("QRImageUrl");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("integer")
                        .HasDefaultValueSql("'Active'::character varying");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("BoothPaymentInfos_pkey");

                    b.HasIndex("BoothId");

                    b.ToTable("BoothPaymentInfos", t =>
                        {
                            t.HasComment("Thông tin tài khoản/QR nhận thanh toán của gian hàng");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.BoothRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BoothName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<Guid?>("PreferredLayoutNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PreferredZoneId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<Guid>("RequestedNightMarketId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PreferredLayoutNodeId");

                    b.HasIndex("PreferredZoneId");

                    b.HasIndex("RequestedNightMarketId");

                    b.ToTable("BoothRegistration");
                });

            modelBuilder.Entity("DomainLayer.Entities.BoothSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("BoothId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'Active'::character varying")
                        .HasComment("Active | Expired | Cancelled");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("BoothSubscriptions_pkey");

                    b.HasIndex("BoothId");

                    b.HasIndex("PackageId");

                    b.ToTable("BoothSubscriptions", t =>
                        {
                            t.HasComment("Lịch sử đăng ký gói dịch vụ của gian hàng");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.Complaint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AdminResponse")
                        .HasColumnType("text");

                    b.Property<Guid>("BoothId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'Open'::character varying")
                        .HasComment("Open | InProgress | Resolved | Rejected");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("Complaints_pkey");

                    b.HasIndex("BoothId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.ToTable("Complaints", t =>
                        {
                            t.HasComment("Khiếu nại của khách hàng về đơn hàng/gian hàng");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.ComplaintImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ComplaintId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("ComplaintImages_pkey");

                    b.HasIndex("ComplaintId");

                    b.ToTable("ComplaintImages", t =>
                        {
                            t.HasComment("Ảnh minh chứng đính kèm theo khiếu nại");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("BoothOwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'Active'::character varying");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("Conversations_pkey");

                    b.HasIndex("BoothOwnerId");

                    b.HasIndex(new[] { "CustomerId", "BoothOwnerId" }, "uq_conversation_customer_boothowner")
                        .IsUnique();

                    b.ToTable("Conversations", t =>
                        {
                            t.HasComment("Cuộc trò chuyện giữa 1 khách hàng và 1 gian hàng - dùng SignalR để realtime");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.FoodCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("FoodCategories_pkey");

                    b.HasIndex(new[] { "Name" }, "FoodCategories_Name_key")
                        .IsUnique();

                    b.ToTable("FoodCategories", t =>
                        {
                            t.HasComment("Danh mục món ăn dùng chung toàn hệ thống");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.FoodImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("FoodImages_pkey");

                    b.HasIndex("FoodItemId");

                    b.ToTable("FoodImages", t =>
                        {
                            t.HasComment("Thư viện ảnh (gallery) cho từng món ăn");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.FoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("BoothId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("false khi món hết nguyên liệu hoặc chủ quán tạm ẩn");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasComment("Giá mặc định. Nếu có FoodPrice theo ngày hiện tại thì giá đó được ưu tiên (override)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("FoodItem_pkey");

                    b.HasIndex(new[] { "BoothId" }, "idx_fooditem_booth");

                    b.HasIndex(new[] { "CategoryId" }, "idx_fooditem_category");

                    b.ToTable("FoodItem", null, t =>
                        {
                            t.HasComment("Món ăn của từng gian hàng");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.FoodPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("FoodPrice_pkey");

                    b.HasIndex("FoodItemId");

                    b.ToTable("FoodPrice", null, t =>
                        {
                            t.HasComment("Bảng giá theo ngày trong tuần - override giá mặc định của FoodItem");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.LayoutEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Distance")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToNodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("LayoutEdges_pkey");

                    b.ToTable("LayoutEdges", t =>
                        {
                            t.HasComment("Cạnh nối giữa 2 LayoutNode - thể hiện đường đi và khoảng cách, dùng cho thuật toán tìm đường ngắn nhất trong chợ");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.LayoutNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uuid");

                    b.Property<string>("NodeName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Xcoordinate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("XCoordinate");

                    b.Property<decimal>("Ycoordinate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("YCoordinate");

                    b.HasKey("Id")
                        .HasName("LayoutNodes_pkey");

                    b.HasIndex("LayoutId");

                    b.ToTable("LayoutNodes", t =>
                        {
                            t.HasComment("Các điểm/nút (node) trên sơ đồ mặt bằng - là đỉnh của đồ thị dùng cho tìm đường nội bộ chợ");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.MarketLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("LayoutImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("NightMarketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("MarketLayouts_pkey");

                    b.HasIndex("NightMarketId");

                    b.ToTable("MarketLayouts", t =>
                        {
                            t.HasComment("Sơ đồ mặt bằng của một chợ đêm - dùng làm nền để đặt các điểm (LayoutNodes) và gian hàng (BoothLocations)");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Snapshot vai trò người gửi: Customer | BoothOwner");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'Text'::character varying")
                        .HasComment("Text | Image | System");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("Message_pkey");

                    b.HasIndex("SenderId");

                    b.HasIndex(new[] { "ConversationId", "CreatedAt" }, "idx_message_conversation");

                    b.ToTable("Message", null, t =>
                        {
                            t.HasComment("Tin nhắn trong cuộc trò chuyện - truyền tải qua SignalR Hub");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.NightMarket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<TimeOnly?>("ClosingHours")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<int?>("MapHeight")
                        .HasColumnType("integer");

                    b.Property<int?>("MapWidth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeOnly?>("OpeningHours")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'Active'::character varying");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TotalBooth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Số lượng gian hàng - giá trị cache, đồng bộ qua trigger hoặc job định kỳ");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("NightMarket_pkey");

                    b.ToTable("NightMarket", null, t =>
                        {
                            t.HasComment("Thông tin các chợ đêm - đơn vị quản lý cấp cao nhất, chứa nhiều Booth");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("BoothId")
                        .HasColumnType("uuid")
                        .HasComment("NULL khi thông báo không gắn với gian hàng cụ thể (VD: thông báo hệ thống)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("NewOrder | OrderStatusChanged | NewMessage | Promotion | System");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("Notification_pkey");

                    b.HasIndex("BoothId");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "idx_notification_user")
                        .IsDescending(false, true);

                    b.ToTable("Notification", null, t =>
                        {
                            t.HasComment("Thông báo đẩy (push notification qua FCM) cho người dùng");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasComment("TotalAmount - DiscountAmount");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PayStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'Pending'::character varying")
                        .HasComment("Pending | Confirmed | Preparing | Completed | Cancelled");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("Order_pkey");

                    b.HasIndex(new[] { "OrderCode" }, "Order_OrderCode_key")
                        .IsUnique();

                    b.HasIndex(new[] { "CustomerId" }, "idx_order_customer");

                    b.ToTable("Order", null, t =>
                        {
                            t.HasComment("Đơn hàng của khách");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasComment("SNAPSHOT giá tại thời điểm đặt hàng - KHÔNG tính lại từ FoodItem.Price");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("OrderDetail_pkey");

                    b.HasIndex("FoodItemId");

                    b.HasIndex(new[] { "OrderId" }, "idx_orderdetail_order");

                    b.ToTable("OrderDetail", null, t =>
                        {
                            t.HasComment("Chi tiết món ăn trong từng đơn hàng");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Package");
                });

            modelBuilder.Entity("DomainLayer.Entities.PackagePrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("PackagePrice");
                });

            modelBuilder.Entity("DomainLayer.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("BoothOwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("'VND'::character varying");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("GatewayRef")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Mã tham chiếu từ cổng thanh toán bên thứ 3 - dùng để tra soát/khiếu nại");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefundReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'Pending'::character varying");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Payment: thu tiền | Refund: hoàn tiền");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("Payments_pkey");

                    b.HasIndex("BoothOwnerId");

                    b.HasIndex(new[] { "OrderId" }, "idx_payments_order");

                    b.ToTable("Payments", t =>
                        {
                            t.HasComment("Lịch sử giao dịch thanh toán/hoàn tiền - tích hợp đa cổng VNPay/ZaloPay/MoMo/Payos");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("BoothId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Percentage: giảm % | FixedAmount: giảm số tiền cố định");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PromotionCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'Active'::character varying");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("Promotion_pkey");

                    b.HasIndex("BoothId");

                    b.ToTable("Promotion", null, t =>
                        {
                            t.HasComment("Chương trình khuyến mãi/mã giảm giá do gian hàng tạo");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.PromotionUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("PromotionUsages_pkey");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.HasIndex(new[] { "PromotionId", "OrderId" }, "uq_promotionusage_order")
                        .IsUnique();

                    b.ToTable("PromotionUsages", t =>
                        {
                            t.HasComment("Lịch sử sử dụng mã khuyến mãi - kiểm tra UsageLimit và chống dùng trùng");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("BoothId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("false: Admin ẩn review nhưng vẫn giữ dữ liệu để tính rating");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("Reviews_pkey");

                    b.HasIndex("CustomerId");

                    b.HasIndex(new[] { "BoothId" }, "idx_reviews_booth");

                    b.HasIndex(new[] { "OrderId" }, "uq_review_order")
                        .IsUnique();

                    b.ToTable("Reviews", t =>
                        {
                            t.HasComment("Đánh giá của khách hàng cho gian hàng, gắn liền với 1 đơn hàng đã hoàn tất");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.ReviewReply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("BoothOwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("ReviewReplies_pkey");

                    b.HasIndex("BoothOwnerId");

                    b.HasIndex(new[] { "ReviewId" }, "ReviewReplies_ReviewId_key")
                        .IsUnique();

                    b.ToTable("ReviewReplies", t =>
                        {
                            t.HasComment("Phản hồi của chủ gian hàng đối với đánh giá - quan hệ 1-1 với Reviews");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("Role_pkey");

                    b.HasIndex(new[] { "RoleName" }, "Role_RoleName_key")
                        .IsUnique();

                    b.ToTable("Role", null, t =>
                        {
                            t.HasComment("Danh sách vai trò người dùng trong hệ thống (Customer, BoothOwner, Admin)");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DoB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Mật khẩu đã được mã hóa (hash), tuyệt đối không lưu plaintext");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("'Active'::character varying")
                        .HasComment("Active: đang hoạt động | Inactive: chưa xác thực | Banned: bị khóa bởi Admin");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id")
                        .HasName("User_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "User_Email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "UserName" }, "User_UserName_key")
                        .IsUnique();

                    b.ToTable("User", null, t =>
                        {
                            t.HasComment("Tài khoản người dùng - dùng chung cho Customer, BoothOwner, Admin (phân biệt qua RoleId)");
                        });
                });

            modelBuilder.Entity("DomainLayer.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("NightMarketId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NightMarketId");

                    b.ToTable("Zone");
                });

            modelBuilder.Entity("DomainLayer.Entities.Booth", b =>
                {
                    b.HasOne("DomainLayer.Entities.User", "BoothOwner")
                        .WithMany("Booths")
                        .HasForeignKey("BoothOwnerId")
                        .IsRequired()
                        .HasConstraintName("Booth_BoothOwnerId_fkey");

                    b.HasOne("DomainLayer.Entities.NightMarket", "NightMarket")
                        .WithMany("Booths")
                        .HasForeignKey("NightMarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Booth_NightMarketId_fkey");

                    b.HasOne("DomainLayer.Entities.BoothRegistration", "Registration")
                        .WithOne("Booth")
                        .HasForeignKey("DomainLayer.Entities.Booth", "RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId");

                    b.Navigation("BoothOwner");

                    b.Navigation("NightMarket");

                    b.Navigation("Registration");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("DomainLayer.Entities.BoothDocument", b =>
                {
                    b.HasOne("DomainLayer.Entities.Booth", null)
                        .WithMany("BoothDocuments")
                        .HasForeignKey("BoothId");

                    b.HasOne("DomainLayer.Entities.BoothRegistration", "Registration")
                        .WithMany("BoothDocuments")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("BoothDocuments_BoothId_fkey");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("DomainLayer.Entities.BoothImage", b =>
                {
                    b.HasOne("DomainLayer.Entities.Booth", "Booth")
                        .WithMany("BoothImages")
                        .HasForeignKey("BoothId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("BoothImages_BoothId_fkey");

                    b.Navigation("Booth");
                });

            modelBuilder.Entity("DomainLayer.Entities.BoothLocation", b =>
                {
                    b.HasOne("DomainLayer.Entities.Booth", "Booth")
                        .WithOne("BoothLocation")
                        .HasForeignKey("DomainLayer.Entities.BoothLocation", "BoothId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("BoothLocations_BoothId_fkey");

                    b.HasOne("DomainLayer.Entities.MarketLayout", "Layout")
                        .WithMany("BoothLocations")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("BoothLocations_LayoutId_fkey");

                    b.Navigation("Booth");

                    b.Navigation("Layout");
                });

            modelBuilder.Entity("DomainLayer.Entities.BoothPaymentInfo", b =>
                {
                    b.HasOne("DomainLayer.Entities.Booth", "Booth")
                        .WithMany("BoothPaymentInfos")
                        .HasForeignKey("BoothId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("BoothPaymentInfos_BoothId_fkey");

                    b.Navigation("Booth");
                });

            modelBuilder.Entity("DomainLayer.Entities.BoothRegistration", b =>
                {
                    b.HasOne("DomainLayer.Entities.User", "Owner")
                        .WithMany("BoothRegistrations")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DomainLayer.Entities.LayoutNode", "PreferredLayoutNode")
                        .WithMany()
                        .HasForeignKey("PreferredLayoutNodeId");

                    b.HasOne("DomainLayer.Entities.Zone", "PreferredZone")
                        .WithMany("BoothRegistrations")
                        .HasForeignKey("PreferredZoneId");

                    b.HasOne("DomainLayer.Entities.NightMarket", "RequestedNightMarket")
                        .WithMany("BoothRegistrations")
                        .HasForeignKey("RequestedNightMarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("PreferredLayoutNode");

                    b.Navigation("PreferredZone");

                    b.Navigation("RequestedNightMarket");
                });

            modelBuilder.Entity("DomainLayer.Entities.BoothSubscription", b =>
                {
                    b.HasOne("DomainLayer.Entities.Booth", "Booth")
                        .WithMany("BoothSubscriptions")
                        .HasForeignKey("BoothId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("BoothSubscriptions_BoothId_fkey");

                    b.HasOne("DomainLayer.Entities.Package", "Package")
                        .WithMany("BoothSubscriptions")
                        .HasForeignKey("PackageId")
                        .IsRequired()
                        .HasConstraintName("BoothSubscriptions_PackageId_fkey");

                    b.Navigation("Booth");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("DomainLayer.Entities.Complaint", b =>
                {
                    b.HasOne("DomainLayer.Entities.Booth", "Booth")
                        .WithMany("Complaints")
                        .HasForeignKey("BoothId")
                        .IsRequired()
                        .HasConstraintName("Complaints_BoothId_fkey");

                    b.HasOne("DomainLayer.Entities.User", "Customer")
                        .WithMany("Complaints")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("Complaints_CustomerId_fkey");

                    b.HasOne("DomainLayer.Entities.Order", "Order")
                        .WithMany("Complaints")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("Complaints_OrderId_fkey");

                    b.Navigation("Booth");

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DomainLayer.Entities.ComplaintImage", b =>
                {
                    b.HasOne("DomainLayer.Entities.Complaint", "Complaint")
                        .WithMany("ComplaintImages")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ComplaintImages_ComplaintId_fkey");

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("DomainLayer.Entities.Conversation", b =>
                {
                    b.HasOne("DomainLayer.Entities.User", "BoothOwner")
                        .WithMany()
                        .HasForeignKey("BoothOwnerId")
                        .IsRequired()
                        .HasConstraintName("Conversations_BoothOwnerId_fkey");

                    b.HasOne("DomainLayer.Entities.User", "Customer")
                        .WithMany("Conversations")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("Conversations_CustomerId_fkey");

                    b.Navigation("BoothOwner");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DomainLayer.Entities.FoodImage", b =>
                {
                    b.HasOne("DomainLayer.Entities.FoodItem", "FoodItem")
                        .WithMany("FoodImages")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FoodImages_FoodItemId_fkey");

                    b.Navigation("FoodItem");
                });

            modelBuilder.Entity("DomainLayer.Entities.FoodItem", b =>
                {
                    b.HasOne("DomainLayer.Entities.Booth", "Booth")
                        .WithMany("FoodItems")
                        .HasForeignKey("BoothId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FoodItem_BoothId_fkey");

                    b.HasOne("DomainLayer.Entities.FoodCategory", "Category")
                        .WithMany("FoodItems")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FoodItem_CategoryId_fkey");

                    b.Navigation("Booth");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DomainLayer.Entities.FoodPrice", b =>
                {
                    b.HasOne("DomainLayer.Entities.FoodItem", "FoodItem")
                        .WithMany("FoodPrices")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FoodPrice_FoodItemId_fkey");

                    b.Navigation("FoodItem");
                });

            modelBuilder.Entity("DomainLayer.Entities.LayoutNode", b =>
                {
                    b.HasOne("DomainLayer.Entities.MarketLayout", "Layout")
                        .WithMany("LayoutNodes")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("LayoutNodes_LayoutId_fkey");

                    b.Navigation("Layout");
                });

            modelBuilder.Entity("DomainLayer.Entities.MarketLayout", b =>
                {
                    b.HasOne("DomainLayer.Entities.NightMarket", "NightMarket")
                        .WithMany("MarketLayouts")
                        .HasForeignKey("NightMarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("MarketLayouts_NightMarketId_fkey");

                    b.Navigation("NightMarket");
                });

            modelBuilder.Entity("DomainLayer.Entities.Message", b =>
                {
                    b.HasOne("DomainLayer.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Message_ConversationId_fkey");

                    b.HasOne("DomainLayer.Entities.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("Message_SenderId_fkey");

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("DomainLayer.Entities.Notification", b =>
                {
                    b.HasOne("DomainLayer.Entities.Booth", "Booth")
                        .WithMany("Notifications")
                        .HasForeignKey("BoothId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("Notification_BoothId_fkey");

                    b.HasOne("DomainLayer.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Notification_UserId_fkey");

                    b.Navigation("Booth");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DomainLayer.Entities.Order", b =>
                {
                    b.HasOne("DomainLayer.Entities.User", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("Order_CustomerId_fkey");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DomainLayer.Entities.OrderDetail", b =>
                {
                    b.HasOne("DomainLayer.Entities.FoodItem", "FoodItem")
                        .WithMany("OrderDetails")
                        .HasForeignKey("FoodItemId")
                        .IsRequired()
                        .HasConstraintName("OrderDetail_FoodItemId_fkey");

                    b.HasOne("DomainLayer.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("OrderDetail_OrderId_fkey");

                    b.Navigation("FoodItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DomainLayer.Entities.PackagePrice", b =>
                {
                    b.HasOne("DomainLayer.Entities.Package", "Package")
                        .WithMany("PackagePrices")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("DomainLayer.Entities.Payment", b =>
                {
                    b.HasOne("DomainLayer.Entities.User", "BoothOwner")
                        .WithMany("Payments")
                        .HasForeignKey("BoothOwnerId")
                        .IsRequired()
                        .HasConstraintName("Payments_BoothOwnerId_fkey");

                    b.HasOne("DomainLayer.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Payments_OrderId_fkey");

                    b.Navigation("BoothOwner");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DomainLayer.Entities.Promotion", b =>
                {
                    b.HasOne("DomainLayer.Entities.Booth", "Booth")
                        .WithMany("Promotions")
                        .HasForeignKey("BoothId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Promotion_BoothId_fkey");

                    b.Navigation("Booth");
                });

            modelBuilder.Entity("DomainLayer.Entities.PromotionUsage", b =>
                {
                    b.HasOne("DomainLayer.Entities.User", "Customer")
                        .WithMany("PromotionUsages")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("PromotionUsages_CustomerId_fkey");

                    b.HasOne("DomainLayer.Entities.Order", "Order")
                        .WithMany("PromotionUsages")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PromotionUsages_OrderId_fkey");

                    b.HasOne("DomainLayer.Entities.Promotion", "Promotion")
                        .WithMany("PromotionUsages")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PromotionUsages_PromotionId_fkey");

                    b.Navigation("Customer");

                    b.Navigation("Order");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("DomainLayer.Entities.Review", b =>
                {
                    b.HasOne("DomainLayer.Entities.Booth", "Booth")
                        .WithMany("Reviews")
                        .HasForeignKey("BoothId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Reviews_BoothId_fkey");

                    b.HasOne("DomainLayer.Entities.User", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("Reviews_CustomerId_fkey");

                    b.HasOne("DomainLayer.Entities.Order", "Order")
                        .WithOne("Review")
                        .HasForeignKey("DomainLayer.Entities.Review", "OrderId")
                        .IsRequired()
                        .HasConstraintName("Reviews_OrderId_fkey");

                    b.Navigation("Booth");

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DomainLayer.Entities.ReviewReply", b =>
                {
                    b.HasOne("DomainLayer.Entities.User", "BoothOwner")
                        .WithMany("ReviewReplies")
                        .HasForeignKey("BoothOwnerId")
                        .IsRequired()
                        .HasConstraintName("ReviewReplies_BoothOwnerId_fkey");

                    b.HasOne("DomainLayer.Entities.Review", "Review")
                        .WithOne("ReviewReply")
                        .HasForeignKey("DomainLayer.Entities.ReviewReply", "ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ReviewReplies_ReviewId_fkey");

                    b.Navigation("BoothOwner");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("DomainLayer.Entities.User", b =>
                {
                    b.HasOne("DomainLayer.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("User_RoleId_fkey");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DomainLayer.Entities.Zone", b =>
                {
                    b.HasOne("DomainLayer.Entities.NightMarket", "NightMarket")
                        .WithMany("Zones")
                        .HasForeignKey("NightMarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NightMarket");
                });

            modelBuilder.Entity("DomainLayer.Entities.Booth", b =>
                {
                    b.Navigation("BoothDocuments");

                    b.Navigation("BoothImages");

                    b.Navigation("BoothLocation");

                    b.Navigation("BoothPaymentInfos");

                    b.Navigation("BoothSubscriptions");

                    b.Navigation("Complaints");

                    b.Navigation("FoodItems");

                    b.Navigation("Notifications");

                    b.Navigation("Promotions");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DomainLayer.Entities.BoothRegistration", b =>
                {
                    b.Navigation("Booth");

                    b.Navigation("BoothDocuments");
                });

            modelBuilder.Entity("DomainLayer.Entities.Complaint", b =>
                {
                    b.Navigation("ComplaintImages");
                });

            modelBuilder.Entity("DomainLayer.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("DomainLayer.Entities.FoodCategory", b =>
                {
                    b.Navigation("FoodItems");
                });

            modelBuilder.Entity("DomainLayer.Entities.FoodItem", b =>
                {
                    b.Navigation("FoodImages");

                    b.Navigation("FoodPrices");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("DomainLayer.Entities.MarketLayout", b =>
                {
                    b.Navigation("BoothLocations");

                    b.Navigation("LayoutNodes");
                });

            modelBuilder.Entity("DomainLayer.Entities.NightMarket", b =>
                {
                    b.Navigation("BoothRegistrations");

                    b.Navigation("Booths");

                    b.Navigation("MarketLayouts");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("DomainLayer.Entities.Order", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("OrderDetails");

                    b.Navigation("Payments");

                    b.Navigation("PromotionUsages");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("DomainLayer.Entities.Package", b =>
                {
                    b.Navigation("BoothSubscriptions");

                    b.Navigation("PackagePrices");
                });

            modelBuilder.Entity("DomainLayer.Entities.Promotion", b =>
                {
                    b.Navigation("PromotionUsages");
                });

            modelBuilder.Entity("DomainLayer.Entities.Review", b =>
                {
                    b.Navigation("ReviewReply");
                });

            modelBuilder.Entity("DomainLayer.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DomainLayer.Entities.User", b =>
                {
                    b.Navigation("BoothRegistrations");

                    b.Navigation("Booths");

                    b.Navigation("Complaints");

                    b.Navigation("Conversations");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("Payments");

                    b.Navigation("PromotionUsages");

                    b.Navigation("ReviewReplies");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DomainLayer.Entities.Zone", b =>
                {
                    b.Navigation("BoothRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
