using ApplicationLayer.DTOs.Responses;
using ApplicationLayer.Exceptions;
using DomainLayer.InterfaceRepository;
using static DomainLayer.Enums.GeneralEnum;

namespace ApplicationLayer.Services.MarketLayouts;

public class LayoutGraphValidationService : ILayoutGraphValidationService
{
    private readonly IMarketLayoutRepository _layouts;
    private readonly ILayoutNodeRepository _nodes;
    private readonly ILayoutEdgeRepository _edges;
    private readonly IBoothLocationRepository _locations;
    public LayoutGraphValidationService(IMarketLayoutRepository layouts, ILayoutNodeRepository nodes,
        ILayoutEdgeRepository edges, IBoothLocationRepository locations)
        => (_layouts, _nodes, _edges, _locations) = (layouts, nodes, edges, locations);

    public async Task<MarketLayoutValidationResponse> ValidateAsync(Guid layoutId, CancellationToken cancellationToken = default)
    {
        var layout = await _layouts.GetActiveByIdAsync(layoutId, cancellationToken)
            ?? throw AppException.NotFound("Market layout was not found.");
        var nodes = await _nodes.GetByLayoutAsync(layoutId, cancellationToken: cancellationToken);
        var edges = await _edges.GetByLayoutAsync(layoutId, cancellationToken: cancellationToken);
        var blocks = await _layouts.GetBlocksByLayoutIdAsync(layoutId, cancellationToken);

        // Layouts generated by earlier releases can contain the same slots and
        // gates as the current model but be missing the internal graph edges.
        // Repair those deterministic links before validating, so a saved layout
        // is not rejected merely because of an old generator implementation.
        var repairedEdges = await RepairGeneratedGraphAsync(layoutId, nodes, edges, cancellationToken);
        if (repairedEdges.Count > 0)
            edges = edges.Concat(repairedEdges).ToArray();

        var locations = await _locations.GetCurrentByLayoutAsync(layoutId, cancellationToken: cancellationToken);

        var errors = new List<string>();
        var warnings = new List<string>();

        // Layout image is optional — canvas-based editors may not need a background image
        if (string.IsNullOrWhiteSpace(layout.LayoutImageUrl))
            warnings.Add("Layout has no background image. Canvas-based layouts can still be activated without one.");

        if (layout.Width <= 0 || layout.Height <= 0)
            errors.Add("Layout width and height must be greater than zero.");

        if (!nodes.Any(x => x.NodeType == LayoutNodeType.Entrance))
            errors.Add("Layout must have at least one entrance.");

        // BoothSlot support: require at least one Junction when booth slots exist.
        // Junctions are auto-generated per Zone by the layout generator; if the market owner
        // manually placed BoothSlots without the generator they must add a Junction manually.
        var boothSlots = nodes.Where(x => x.NodeType == LayoutNodeType.BoothSlot).ToList();
        if (boothSlots.Count > 0 && !nodes.Any(x => x.NodeType == LayoutNodeType.Junction))
            errors.Add("Layout must have at least one path point (junction). Use the Generate Layout feature or add one manually.");

        // BoothAccess is a retired, legacy-only node type. Existing rows are retained
        // for compatibility but do not affect whether a modern Gate-based layout can
        // be activated.

        if (nodes.Any(x => x.Xcoordinate < 0 || x.Xcoordinate > layout.Width || x.Ycoordinate < 0 || x.Ycoordinate > layout.Height))
            errors.Add("All nodes must be inside the layout dimensions.");

        if (blocks.Any(b => b.X < 0 || b.Y < 0 || b.X + b.Width > layout.Width || b.Y + b.Height > layout.Height))
            errors.Add("All blocks must be inside the layout dimensions.");

        if (edges.Any(x => x.FromNodeId == x.ToNodeId))
            errors.Add("Edges cannot connect a node to itself.");

        if (edges.GroupBy(x => x.FromNodeId.CompareTo(x.ToNodeId) < 0
                ? (x.FromNodeId, x.ToNodeId)
                : (x.ToNodeId, x.FromNodeId))
            .Any(x => x.Count() > 1))
            errors.Add("Layout contains duplicate edges.");

        var nodeIds = nodes.Select(x => x.Id).ToHashSet();

        if (edges.Any(x => !nodeIds.Contains(x.FromNodeId) || !nodeIds.Contains(x.ToNodeId)))
            errors.Add("All edge endpoints must belong to this layout.");

        var connectedIds = edges.SelectMany(x => new[] { x.FromNodeId, x.ToNodeId }).ToHashSet();

        // A Gate (stored as Entrance) and each booth slot must be connected. Retired
        // BoothAccess records from an older layout are deliberately ignored here.
        if (nodes.Any(x => (x.NodeType is LayoutNodeType.Entrance or LayoutNodeType.BoothSlot) && !connectedIds.Contains(x.Id)))
            errors.Add("Each gate and booth slot must be connected to the layout.");

        var reachable = ReachableFromEntrances(nodes.Where(x => x.NodeType == LayoutNodeType.Entrance).Select(x => x.Id), edges);

        // Every BoothSlot must be reachable from an entrance
        if (boothSlots.Any(bs => !reachable.Contains(bs.Id)))
            errors.Add("Every booth slot must be reachable from an entrance.");

        // SlotCode validation for BoothSlots
        var slotsWithEmptyCode = boothSlots.Where(x => string.IsNullOrWhiteSpace(x.SlotCode)).ToList();
        if (slotsWithEmptyCode.Count > 0)
            errors.Add("Every booth slot must have a slot code.");

        var duplicateCodes = boothSlots
            .Where(x => !string.IsNullOrWhiteSpace(x.SlotCode))
            .GroupBy(x => x.SlotCode!, StringComparer.OrdinalIgnoreCase)
            .Where(g => g.Count() > 1)
            .Select(g => g.Key)
            .ToList();
        if (duplicateCodes.Count > 0)
            errors.Add($"Duplicate slot codes: {string.Join(", ", duplicateCodes)}.");

        if (locations.Any(x => !nodeIds.Contains(x.LayoutNodeId)))
            errors.Add("A booth location references an invalid node.");

        if (nodes.Count == 0)
            errors.Add("Layout must have at least one node.");

        if (edges.Count == 0)
            warnings.Add("Layout has no paths.");

        if (boothSlots.Count == 0)
            warnings.Add("Layout has no booth slots. Customers will not be able to find booths.");

        return new() { Errors = errors.Distinct().ToList(), Warnings = warnings };
    }

    private async Task<IReadOnlyCollection<DomainLayer.Entities.LayoutEdge>> RepairGeneratedGraphAsync(
        Guid layoutId,
        IReadOnlyCollection<DomainLayer.Entities.LayoutNode> nodes,
        IReadOnlyCollection<DomainLayer.Entities.LayoutEdge> edges,
        CancellationToken cancellationToken)
    {
        var gates = nodes.Where(node => node.NodeType == LayoutNodeType.Entrance).ToList();
        var junctions = nodes.Where(node => node.NodeType == LayoutNodeType.Junction).ToList();
        if (gates.Count == 0 || junctions.Count == 0)
            return [];

        var nodeIds = nodes.Select(node => node.Id).ToHashSet();
        var validEdges = edges.Where(edge => nodeIds.Contains(edge.FromNodeId) && nodeIds.Contains(edge.ToNodeId)).ToList();
        var pairs = validEdges.Select(CanonicalPair).ToHashSet();
        var additions = new List<DomainLayer.Entities.LayoutEdge>();

        void AddLink(DomainLayer.Entities.LayoutNode from, DomainLayer.Entities.LayoutNode to)
        {
            if (from.Id == to.Id || !pairs.Add(CanonicalPair(from.Id, to.Id))) return;
            var distance = Math.Sqrt(Math.Pow((double)(from.Xcoordinate - to.Xcoordinate), 2) +
                                     Math.Pow((double)(from.Ycoordinate - to.Ycoordinate), 2));
            additions.Add(new DomainLayer.Entities.LayoutEdge
            {
                Id = Guid.NewGuid(),
                LayoutId = layoutId,
                FromNodeId = from.Id,
                ToNodeId = to.Id,
                Distance = (decimal)distance,
                IsBidirectional = true,
                IsAccessible = true,
                IsDeleted = false,
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow
            });
        }

        // Every gate needs an entry point into the generated zone graph. AddLink
        // is pair-idempotent, so this never duplicates an existing correct edge.
        foreach (var gate in gates)
            AddLink(gate, Nearest(gate, junctions));

        // Each generated slot belongs to its zone junction. Use the nearest
        // junction only for pre-zone legacy rows that have no ZoneId/block ID.
        foreach (var slot in nodes.Where(node => node.NodeType == LayoutNodeType.BoothSlot))
        {
            var zoneJunction = junctions.FirstOrDefault(junction =>
                (slot.LayoutBlockId.HasValue && junction.LayoutBlockId == slot.LayoutBlockId) ||
                (slot.ZoneId.HasValue && junction.ZoneId == slot.ZoneId));
            AddLink(slot, zoneJunction ?? Nearest(slot, junctions));
        }

        // Join disconnected zone junctions into the gate-connected component.
        // The edges are internal routing metadata; the simplified UI does not
        // draw them in the assignment screen.
        var allEdges = validEdges.Concat(additions).ToList();
        var reachable = ReachableFromEntrances(gates.Select(gate => gate.Id), allEdges);
        foreach (var junction in junctions.Where(junction => !reachable.Contains(junction.Id)))
        {
            var sourceCandidates = nodes.Where(node => reachable.Contains(node.Id)).ToList();
            if (sourceCandidates.Count == 0) break;
            AddLink(Nearest(junction, sourceCandidates), junction);
            allEdges = validEdges.Concat(additions).ToList();
            reachable = ReachableFromEntrances(gates.Select(gate => gate.Id), allEdges);
        }

        if (additions.Count > 0)
        {
            await _edges.AddRangeAsync(additions);
            await _edges.SaveChangesAsync();
        }

        return additions;
    }

    private static DomainLayer.Entities.LayoutNode Nearest(
        DomainLayer.Entities.LayoutNode origin,
        IEnumerable<DomainLayer.Entities.LayoutNode> candidates)
        => candidates.OrderBy(candidate =>
                Math.Pow((double)(candidate.Xcoordinate - origin.Xcoordinate), 2) +
                Math.Pow((double)(candidate.Ycoordinate - origin.Ycoordinate), 2))
            .First();

    private static (Guid First, Guid Second) CanonicalPair(DomainLayer.Entities.LayoutEdge edge)
        => CanonicalPair(edge.FromNodeId, edge.ToNodeId);

    private static (Guid First, Guid Second) CanonicalPair(Guid first, Guid second)
        => first.CompareTo(second) < 0 ? (first, second) : (second, first);

    private static HashSet<Guid> ReachableFromEntrances(IEnumerable<Guid> starts, IEnumerable<DomainLayer.Entities.LayoutEdge> edges)
    {
        var graph = new Dictionary<Guid, List<Guid>>();
        foreach (var edge in edges.Where(x => x.IsAccessible))
        {
            graph.TryAdd(edge.FromNodeId, []); graph[edge.FromNodeId].Add(edge.ToNodeId);
            if (edge.IsBidirectional) { graph.TryAdd(edge.ToNodeId, []); graph[edge.ToNodeId].Add(edge.FromNodeId); }
        }
        var visited = starts.ToHashSet();
        var queue = new Queue<Guid>(visited);
        while (queue.TryDequeue(out var current))
            if (graph.TryGetValue(current, out var adjacent))
                foreach (var next in adjacent)
                    if (visited.Add(next)) queue.Enqueue(next);
        return visited;
    }
}
